module.exports = {
  model: 'Coach',
  clearBeforeUpdate: true,
  data: [
    {
      email: 'Tumuruo@localhost.com',
      password: '123456',
      firstName: 'Alex',
      lastName: 'Tumuruo',
      phoneNumber: '+375(29)8826569',
      role: 'Coach',
      status: 'Available',
    },
    {
      email: 'Dex@localhost.com',
      password: '123456',
      firstName: 'Jay',
      lastName: 'Dex',
      phoneNumber: '+375(29)5876449',
      role: 'Coach',
      status: 'Available',
    },
    {
      email: 'Fox@localhost.com',
      password: '123456',
      firstName: 'Lia',
      lastName: 'Fox',
      phoneNumber: '+375(29)8776549',
      role: 'Coach',
      status: 'Available',
    },
    {
      email: 'Korj@localhost.com',
      password: '123456',
      firstName: 'Angelina',
      lastName: 'Korj',
      phoneNumber: '+375(29)6676549',
      role: 'Coach',
      status: 'Available',
    },
    {
      email: 'Petrov@localhost.com',
      password: '123456',
      firstName: 'Denis',
      lastName: 'Petrov',
      phoneNumber: '+375(29)3276569',
      role: 'Coach',
      status: 'Available',
    },
  ],
};
